-- Rename DocumentTemplate names to match Kelly's exact nomenclature
UPDATE "DocumentTemplate" SET nom = 'ATTESTATION DE RESPONSABILITE CIVILE' WHERE nom = 'ATTESTATION RC PROFESSIONNELLE';
UPDATE "DocumentTemplate" SET nom = 'ASSURANCE SINISTRALITE SUR 4 ANS' WHERE nom LIKE 'ASSURANCE SINISTRAL%';
UPDATE "DocumentTemplate" SET nom = 'ATTESTATION SECURITE SOCIALE DES INDEPENDANT' WHERE nom LIKE 'ATTESTATION S%CU%IND%';
UPDATE "DocumentTemplate" SET nom = 'ATTESTATION CAISSE DE CONGES PAYES (CIBTP)' WHERE nom LIKE 'ATTESTATION CONG%';
UPDATE "DocumentTemplate" SET nom = 'ATTESTATION DECENNALE' WHERE nom LIKE 'ATTESTATION D%CENNALE';
UPDATE "DocumentTemplate" SET nom = 'DIPLOMES ET FORMATIONS' WHERE nom LIKE 'DIPL%MES%';
UPDATE "DocumentTemplate" SET nom = 'DEVIS CONFORME - Renseignement administratif obligatoire' WHERE nom = 'DEVIS CONFORME';
UPDATE "DocumentTemplate" SET nom = 'FACTURE CONFORME - Renseignement obligatoire' WHERE nom = 'FACTURE CONFORME';
UPDATE "DocumentTemplate" SET nom = 'ATTESTATION DE REUSSITE RGE (SCORE: 24 et plus)' WHERE nom LIKE 'ATTESTATION R%USSITE%';

-- Add MANDAT if not exists
INSERT INTO "DocumentTemplate" ("id", "nom", "type", "obligatoire", "ordre")
VALUES ('dt-commun-mandat', 'MANDAT', 'TRONC_COMMUN', true, 0)
ON CONFLICT ("id") DO NOTHING;

-- Rename existing Document records too
UPDATE "Document" SET nom = 'ATTESTATION DE RESPONSABILITE CIVILE' WHERE nom = 'ATTESTATION RC PROFESSIONNELLE';
UPDATE "Document" SET nom = 'ASSURANCE SINISTRALITE SUR 4 ANS' WHERE nom LIKE 'ASSURANCE SINISTRAL%';
UPDATE "Document" SET nom = 'ATTESTATION SECURITE SOCIALE DES INDEPENDANT' WHERE nom LIKE 'ATTESTATION S%CU%IND%';
UPDATE "Document" SET nom = 'ATTESTATION CAISSE DE CONGES PAYES (CIBTP)' WHERE nom LIKE 'ATTESTATION CONG%';
UPDATE "Document" SET nom = 'ATTESTATION DECENNALE' WHERE nom LIKE 'ATTESTATION D%CENNALE';
UPDATE "Document" SET nom = 'DIPLOMES ET FORMATIONS' WHERE nom LIKE 'DIPL%MES%';
UPDATE "Document" SET nom = 'DEVIS CONFORME - Renseignement administratif obligatoire' WHERE nom = 'DEVIS CONFORME';
UPDATE "Document" SET nom = 'FACTURE CONFORME - Renseignement obligatoire' WHERE nom = 'FACTURE CONFORME';
UPDATE "Document" SET nom = 'ATTESTATION DE REUSSITE RGE (SCORE: 24 et plus)' WHERE nom LIKE 'ATTESTATION R%USSITE%';
