ALTER TABLE "Entreprise" ADD COLUMN "relanceJoindre1" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceJoindre1" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceJoindre2" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceJoindre2" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceJoindre3" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceJoindre3" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceJoindre4" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceJoindre4" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceJoindreInjoignable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceJoindreInjoignable" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceDevis1" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceDevis1" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceDevis2" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceDevis2" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceDevis3" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceDevis3" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceDevis4" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceDevis4" TIMESTAMP(3);
ALTER TABLE "Entreprise" ADD COLUMN "relanceDevisFerme" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Entreprise" ADD COLUMN "dateRelanceDevisFerme" TIMESTAMP(3);
