ALTER TYPE "TypeAlerte" ADD VALUE 'MENTION';

ALTER TABLE "Alerte" ADD COLUMN "noteId" TEXT;
ALTER TABLE "Alerte" ADD CONSTRAINT "Alerte_noteId_fkey"
    FOREIGN KEY ("noteId") REFERENCES "Note"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
